#Begin: Configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-deployment-init-configmap
data:
  mysql-init.sql: |
    CREATE TABLE `products` (
      `mission` VARCHAR(30) NOT NULL,
      `description`  VARCHAR(5000),
      `heading` VARCHAR(1000),
      PRIMARY KEY (`product`)
    );

    CREATE TABLE `popular` (
      `mission` VARCHAR(30) NOT NULL,
      `count` BIGINT,
       PRIMARY KEY (`product`)
    );

    INSERT INTO products (product, description, heading) VALUES ('p-1', 'This is the future of communication. Call from everywhere.','mobilephone1')
    INSERT INTO products (product, description, heading) VALUES ('p-2, 'This is the future of working. Work from everywhere.','laptop1')
    INSERT INTO products (product, description, heading) VALUES ('p-3', 'This is the future of media consumption. Watch your favorite show from everywhere.','tablet1')
    INSERT INTO products (product, description, heading) VALUES ('p-4', 'This is the future of call quality. Listen and speak in your calls without cord.','wirelessheadset1')
    INSERT INTO products (product, description, heading) VALUES ('p-5', 'This is the future of navigating your OS. Steer your mouse by laser.','mouse1')
    INSERT INTO products (product, description, heading) VALUES ('p-6', 'This is the future of writing.','keyboard1')
    INSERT INTO products (product, description, heading) VALUES ('p-7', 'This is the future of charging. Charge your accessories everywhere.','charger1')
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  labels:
    app: my-mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-mysql
  template:
    metadata:
      labels:
        app: my-mysql
    spec:
      containers:
        - name: my-mysql
          image: mysql
          # Set required environment variables to initialize the container
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "mysecretpw"
            - name: MYSQL_DATABASE
              value: "popular"
          ports:
            - containerPort: 33060
          # Mount the volume
          # Mount configmap at expected location (excerpt)
          volumeMounts:
            - name: init-volume
              mountPath: /docker-entrypoint-initdb.d/
      volumes:
        - name: init-volume
          configMap:
            name: mysql-deployment-init-configmap

---
#Begin: Service
apiVersion: v1
kind: Service
metadata:
  name: my-app-mysql-service
spec:
  selector:
    app: my-mysql
  ports:
    - name: mysql-xproto
      protocol: TCP
      port: 33060
      targetPort: 33060
#End: Service
